### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by Chocksy** [EpicCoders/epiclogger#129]
- [x] in aggregates we have the tables that define each section. We should remove the "Message" or adjust it depending on what section we are on. The idea is that message doesn't work for browsers or subscribers. 
- [x] we need to default the tab of the error sidebar to unresolved when visiting an error page
- [x] we need an active state on the visible error in the sidebar
- [x] the active state should work even if the error is on the second page on the sidebar and you visit it from the errors#index
- [x] the chart that shows the number of occurences should start from the bottom always:  ![image](https://cloud.githubusercontent.com/assets/178892/15505445/4a88f516-21cc-11e6-80dc-0ad93622a4f1.png)
- [x] add break-word css rule for the text so the right sidebar with details does not get out of bounds
- [x] If we have multiple errors and pages make the buttons for select all and resolve be on the line with the pagination buttons ![image](https://cloud.githubusercontent.com/assets/178892/15505492/70267712-21cc-11e6-80a3-8a7dafea59bc.png)
- [x] don't change the sidebar tab when moving to aggregations
- [x] at 970px-1200px width (tablet view) there is a weird spacing to the right of the errors#index table: ![image](https://cloud.githubusercontent.com/assets/178892/15505578/c0cb16be-21cc-11e6-9a5b-3899e9dcca3a.png)
- [x] if i click to resolve an error that error should dissapear from the sidebar and move to the right list (resolved/unresolved). 
- [x] make the icons on the small sidebar (general sidebar) smaller with `font-size: 20px` 
- [x] the number of times each error occured in the error list seem to be fixed and look weird if you scroll down (http://www.screencast.com/t/H0V4McJ6)
  -[ ] add an error message response to the sidebar resolve/unresolve form if its being submitted without any selections
  -[ ] fix an issue with the error sidebar where it exceeds the limit of 5 elements if we press the resolve button on the error page multiple times.
  -[ ] on the errors sidebar, when resolving elements on the last page it should load the errors on the previous page and update the pagination

**Comment by hyperionel** [comment]
Fixed the ones above. I'll add these here since they're related.
- [ ] add an error message response to the sidebar resolve/unresolve form if its being submitted without any selections
- [ ] fix an issue with the error sidebar where it exceeds the limit of 5 elements if we press the resolve button on the error page multiple times.
- [ ] on the errors sidebar, when resolving elements on the last page it should load the errors on the previous page and update the pagination
