### ISSUE TITLE
Improve aggregations code to be more dynamic

### ISSUE THREAD

**Issue by Chocksy** [EpicCoders/epiclogger#141]
The aggregations code is not as dynamic as it should. 
- [x] The idea is to define the table attributes by the hash that is generated from the data.
- [x] As if we would like to add another aggregated element of data we would not modify the tab at all
- [x] The aggregated data should also be dynamic and defined by some arguments passed to a method instead of doing some manual stuff. This can be achieved by doing a block method that would take some custom code if required

**Comment by Chocksy** [comment]
@ungureanu-bogdan-sorin what's up with this?

**Comment by hyperionel** [comment]
@chocksy forgot to create a pull request for this...making one now
