### ISSUE TITLE
Fix these bugs

### ISSUE THREAD

**Issue by hyperionel** [EpicCoders/epiclogger#151]
- [x] The account icon does not open the submenu in the minimised sidebar(when on errors#show)
- [x] Signing in with github pops-up the Add Website wizard even if the account already has a website.
- [x] Add some error messages for the Add Website wizard (ex. domain already exists)

**Comment by hyperionel** [comment]
The fix for the wizard being displayed if the user already has a website is in the feat-integrations branch since it relied on the auth_controller. The other two are in the feat-debugging branch.

**Comment by Chocksy** [comment]
@ungureanu-bogdan-sorin ok thanks.
