### ISSUE TITLE
assigned.website nu se apeleaza cand avem 2 cookies picked_website

### ISSUE THREAD

**Issue by Chocksy** [EpicCoders/epiclogger#18]
Atunci cand ne logam cu un user si avem siteurile se seteaza un cookie picked_website cu o valoarea. Apoi daca iesim din website (logout) si intram cu alt user se seteaza alt picked_website (2 cookies) cu alta valoarea si picked_website nu se mai apeleaza. 

Solutie. Atunci cand intram cu un user (login) resetam cookie picked_website (stergem cookie) si apoi lasam codul sa seteze cookie de la sine.

**Comment by aurelianb** [comment]
Nu ar fi o solutie mai ok ca cookie-ul sa fie sters la logout decat la login? De asemenea, ar trebui setat un expiry-time de 14 zile (identic cu cel al cookie-ului de sesiune) cand se seteaza cookie-ul de pickedWebsite.

**Comment by Chocksy** [comment]
@aurelianb merci de comment. E mai bine la logout asa e, astfel ordinea de executie nu conteaza.
