### ISSUE TITLE
We need just one button for status

### ISSUE THREAD

**Issue by Chocksy** [EpicCoders/epiclogger#45]
Right now we have 2 buttons resolved and mark resolved in the error page.

The right way this should work is have mark resolved if the error is unresolved and show resolved when it's resolved. If you hover over resolved it should change to unresolve to allow the user to revert the change.

![Alt text](https://monosnap.com/file/786fJxhqdIapHAYKwYezyURywwmWeg.png)

**Comment by Panioglo** [comment]
I've changed that, Resolved success button(disabled) appears only when issue is marked as resolved. Mark resolved becomes hidden.

**Comment by Panioglo** [comment]
Pull improve_errors_view branch.
